name: CI/CD Pipeline

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    branches: [ dev ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7-dind

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get lowercase repo
        id: repo
        run: echo "repo=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Get workload SHA
        id: workload_sha
        run: echo "workload_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Check if workload changed
        id: workload-changed
        run: |
          if [ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ] || [ -z "${{ github.event.before }}" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^frontend/')
            if [ -n "$CHANGED_FILES" ]; then
              echo "changed=true" >> $GITHUB_OUTPUT
            else
              echo "changed=false" >> $GITHUB_OUTPUT
            fi
          fi
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22  # or your project's Node version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Run linting checks
        run: npm run lint

      - name: Build workload Docker image
        if: steps.workload-changed.outputs.changed == 'true'
        run: |
          docker build -t ghcr.io/${{ steps.repo.outputs.repo }}/workload:${{ steps.workload_sha.outputs.workload_sha }} .